moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - my_planning_group_controller

my_planning_group_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint_1
    - joint_3
    - joint_5
    - joint_7
    - joint_9
    - joint_11
    - joint_13

