controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    my_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster 

my_planning_group_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_3
      - joint_5
      - joint_7
      - joint_9
      - joint_11
      - joint_13
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

joint_state_broadcaster:
  ros__parameters: {}





